CREATE OR REPLACE TABLE RAW.ORDERS (
    ORDER_ID        VARCHAR,
    CUSTOMER_ID     VARCHAR,
    ORDER_DATE      VARCHAR,
    AMOUNT          VARCHAR,
    STATUS          VARCHAR,
    BATCH_ID        VARCHAR,
    LOAD_TIMESTAMP  TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);