COPY INTO RAW.ORDERS
FROM (
    SELECT
        $1 AS ORDER_ID,
        $2 AS CUSTOMER_ID,
        $3 AS ORDER_DATE,
        $4 AS AMOUNT,
        $5 AS STATUS,
        TO_VARCHAR(CURRENT_TIMESTAMP(), 'YYYYMMDDHH24MISS') AS BATCH_ID,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
    FROM @RAW.raw_stage
)
FILE_FORMAT = (
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
)
PATTERN = '.*orders_.*\.csv';