CREATE OR REPLACE TABLE STAGING.ORDERS_CLEAN AS
WITH casting AS (
    SELECT
        TRY_TO_NUMBER(ORDER_ID) AS ORDER_ID,
        TRY_TO_NUMBER(CUSTOMER_ID) AS CUSTOMER_ID,
        TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
        TRY_TO_NUMBER(AMOUNT) AS AMOUNT,
        UPPER(TRIM(STATUS)) AS STATUS,
        BATCH_ID,
        LOAD_TIMESTAMP
    FROM RAW.ORDERS
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    AMOUNT,
    STATUS,

    CASE WHEN ORDER_ID IS NOT NULL THEN 1 ELSE 0 END AS DQ_ORDER_ID,
    CASE WHEN CUSTOMER_ID IS NOT NULL THEN 1 ELSE 0 END AS DQ_CUSTOMER_ID,
    CASE WHEN ORDER_DATE IS NOT NULL THEN 1 ELSE 0 END AS DQ_ORDER_DATE,
    CASE WHEN AMOUNT IS NOT NULL AND AMOUNT > 0 THEN 1 ELSE 0 END AS DQ_AMOUNT,
    CASE WHEN STATUS IN ('COMPLETED','PENDING','CANCELLED') THEN 1 ELSE 0 END AS DQ_STATUS,

    CASE
        WHEN ORDER_ID IS NOT NULL
         AND CUSTOMER_ID IS NOT NULL
         AND ORDER_DATE IS NOT NULL
         AND AMOUNT IS NOT NULL
         AND AMOUNT > 0
         AND STATUS IN ('COMPLETED','PENDING','CANCELLED')
        THEN 1 ELSE 0
    END AS DQ_FINAL_CHECK,

    BATCH_ID,
    LOAD_TIMESTAMP
FROM casting;