CREATE OR REPLACE TABLE STAGING.ORDERS_CLEAN AS
SELECT
    TRY_TO_NUMBER(ORDER_ID) AS ORDER_ID,
    TRY_TO_NUMBER(CUSTOMER_ID) AS CUSTOMER_ID,
    TRY_TO_DATE(ORDER_DATE) AS ORDER_DATE,
    TRY_TO_NUMBER(AMOUNT) AS AMOUNT,
    UPPER(TRIM(STATUS)) AS STATUS,
    BATCH_ID,
    LOAD_TIMESTAMP
FROM RAW.ORDERS;